export  const HOME_CASUAL = 'home_casual'
export  const HOME_NAV = 'home_nav'
export  const HOME_LIST = 'home_list'
export  const RECOMMEND_LIST = 'recommend_list'
export  const SEARCH_GOODS = 'search_goods'
